name: Bug Report
description: Describe the bug you encountered.
title: "🐞 "
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: bug-type
    attributes:
      label: 🐞 Bug Type
      description: 어떤 종류의 문제인가요?
      multiple: true
      options:
        - 🐞 오류 (에러, 예외 발생, 논리적 오류 등)
        - 🏗 컨벤션·리팩터링 (코드 스타일, 아키텍처 등)
        - ⚡️ 성능 (지연, 과도한 자원, 병목 현상 등)
        - ✏️ 오타·설명 오류 (문서, 문자열, 주석, 식별자 등)
        - 🔧 기타 (빌드, 환경변수 등)
        - "❗️ 보안 취약점은 pkw19961027@gmail.com으로 메일 부탁드립니다."
      default: 0
    validations:
      required: true
  - type: input
    id: summary
    attributes:
      label: 💬 Summary of the Bug
      description: 버그를 한 문장 정도로 요약해 주세요.
      placeholder: ex. 로그인 후 화면이 멈춥니다.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔁 오류 재현 (Reproduction Steps)
      description: 버그를 재현하기 위한 구체적인 단계들을 순서대로 적어 주세요.
      value: |
        
        1. 
        2. 
        3. 
        
        <br />
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 📝 관련 로그 (Logs)
      description: 에러 메시지나 로그가 있다면 복사해서 붙여 주세요.
      placeholder: |
        Error: Cannot read property 'foo' of undefined
          at …
      render: console
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: 🎯 기대 동작 (Expected Behavior)
      description: 정상적으로 동작했을 때 어떤 결과가 나와야 하는지 설명해 주세요.
      placeholder: ex. 로그인 후 대시보드 페이지가 보여야 합니다.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: 🔍 실제 동작 (Actual Behavior)
      description: 어떤 동작이 나타나는지 설명해 주세요.
      placeholder: ex. 로그인 후 버튼이 반응하지 않습니다.
    validations:
      required: true
  - type: textarea
    id: additional-note
    attributes:
      label: 부연 설명 (Additional Notes)
      description: Active profile, 환경변수 등 기타 참고할 만한 정보가 있으면 적어 주세요.
      placeholder: Tell us any other details you think will help us fix this!
      value: |
        
        ### 실행 환경 (Environment)
        
        - Active Profiles: (none)
        
        <details open><summary>Environment variables</summary>
        
        (none)
        
        </details>
        
        <br />
    validations:
      required: false
