spring:
  application:
    name: main

  config:
    import:
      - properties/web/main.cors.yml
      - properties/persistence/main.snowflake.yml
      - properties/client/main.client.yml
      - board.yml

server:
  port: 5000

