spring:
  application:
    name: main

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${BOARD_POSTGRESQL_URL}
    username: ${BOARD_POSTGRESQL_USERNAME}
    password: ${BOARD_POSTGRESQL_PASSWORD}

  config:
    import:
      - properties/web/main.cors.yml
      - properties/persistence/main.snowflake.yml
      - properties/client/main.client.yml
#      - board.yml # NOTE this is for MSA projects (delete this line after confirmed)

  flyway:
    baseline-on-migrate: true
    locations:
      - db/migration/v1_0

server:
  port: 5000

