spring:
  application:
    name: main

  config:
    import:
      - properties/web/main.cors.yml
      - properties/persistence/main.snowflake.yml
      - board.yml
      - article.yml

server:
  port: 5000

