spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${COMMENT_POSTGRESQL_URL:jdbc:postgresql://localhost:5433/demo}
    username: ${COMMENT_POSTGRESQL_USERNAME:root}
    password: ${COMMENT_POSTGRESQL_PASSWORD:root}

  flyway:
    baseline-on-migrate: true
    locations:
      - db/postgresql/migration/v1_0