spring:
  datasource:
    url: ${BOARD_POSTGRESQL_URL:jdbc:postgresql://localhost:5433/demo}
    username: ${BOARD_POSTGRESQL_USERNAME:root}
    password: ${BOARD_POSTGRESQL_PASSWORD:root}

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  flyway:
    baseline-on-migrate: true
    locations:
      - db/postgresql/migration/v1_0
